-- migration_027: Expand allowed values for orders.source
-- Adds 'paypal' and 'wire' as valid order sources alongside existing values.

-- Drop the old check constraint (name generated by Postgres from the inline CHECK)
ALTER TABLE public.orders
  DROP CONSTRAINT IF EXISTS orders_source_check;

-- Re-add with the expanded list
ALTER TABLE public.orders
  ADD CONSTRAINT orders_source_check
  CHECK (source IN ('stripe', 'whatsapp', 'cash', 'paypal', 'wire', 'custom', 'admin'));
